#!/bin/sh
sudo insmod driver-02.ko
MAJOR=`dmesg | tail -n 1 | awk "{print \\$5}"`
if [ -z $MAJOR ]; then
   MAJOR=`dmesg | tail -n 1 | awk "{print \\$4}"`
fi
sudo mknod /dev/arr_dev_02 c $MAJOR 0
sudo chmod a+w /dev/arr_dev_02
